# Generated by Django 6.0.3 on 2026-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('director', 'Руководитель')], db_column='Roles_ID', default='teacher', max_length=20),
        ),
    ]
