# Generated by Django 6.0.3 on 2026-03-05 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'criterions',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('end_date', models.CharField(blank=True, db_column='End_date', max_length=255, null=True)),
                ('name', models.CharField(db_column='Name', max_length=20, unique=True)),
                ('start_date', models.DateTimeField(db_column='Start_date', unique=True)),
                ('status', models.BooleanField(db_column='Status')),
            ],
            options={
                'db_table': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time_of_addition', models.DateTimeField(db_column='Time_of_addition')),
                ('user', models.ForeignKey(db_column='Users_ID', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(db_column='PeriodsID', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.period')),
                ('work', models.ForeignKey(db_column='WorksID', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.work')),
            ],
            options={
                'db_table': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('caption', models.CharField(db_column='Caption', max_length=255)),
                ('criterion', models.ForeignKey(db_column='criterionsID', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.criterion')),
                ('field_type', models.ForeignKey(db_column='TypesID', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.type')),
            ],
            options={
                'db_table': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='AchievementFieldValue',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.CharField(db_column='Value', max_length=1000)),
                ('achievement', models.ForeignKey(db_column='Achievements_ID', on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='main.achievement')),
                ('field', models.ForeignKey(db_column='Fields_ID', on_delete=django.db.models.deletion.CASCADE, related_name='achievement_values', to='main.field')),
            ],
            options={
                'db_table': 'AchievementFieldValues',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('caption', models.CharField(db_column='Caption', max_length=255)),
                ('ratio', models.FloatField(db_column='Ratio')),
                ('field', models.ForeignKey(db_column='FieldsID', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='main.field')),
            ],
            options={
                'db_table': 'Levels',
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='work',
            field=models.ForeignKey(db_column='WorksID', on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='main.work'),
        ),
    ]
