# Generated by Django 6.0.3 on 2026-03-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_criterion_period_type_work_achievement_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
