# Generated by Django 6.0.3 on 2026-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_field_field_type_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'текст'), ('chooser', 'выбиралка'), ('photo', 'фото')], db_column='Type', default='text', max_length=20),
        ),
    ]
